version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app1
  mysql-db:
    image: mysql
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: Holahola44#
      MYSQL_DATABASE: default
    ports:
      - 33060:3306
  app1:
    container_name: milkstgo1
    image: alephzer0/milkstgo
    ports:
      - "8091:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/root?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Holahola44#
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql-db